<a href="https://colab.research.google.com/github/shubhamlad21/msc1_fds_512/blob/main/13_08_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd

In [6]:
a=np.array([1,2,3])                                     
print(a)
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3


In [13]:
b=np.array([[1,2],[3,4]])
print(b)
print(b.shape)
print(b[0,0],b[0,1])

[[1 2]
 [3 4]]
(2, 2)
1 2


In [14]:
c=np.array([[1,2],[3,4],[5,6]])
print(c)
print(c[0,0],c[0,1],c[2,0],c[2,1])

[[1 2]
 [3 4]
 [5 6]]
1 2 5 6


In [15]:
d=np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
e=np.ones((4,2))
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
f=np.full((2,2),9)
print(f)

[[9 9]
 [9 9]]


In [18]:
g=np.random.random((3,3))
print(g)

[[0.53508049 0.65224055 0.33747543]
 [0.92557416 0.87519918 0.47060827]
 [0.3398651  0.57639306 0.54592793]]


In [19]:
h=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
i=h[:2,1:3]
print(i)

[[2 3]
 [6 7]]
