<a href="https://colab.research.google.com/github/shubhamlad21/msc1_fds_512/blob/main/FDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**13_08_2022**

---



In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a=np.array([1,2,3])                                     
print(a)
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3


In [ ]:
b=np.array([[1,2],[3,4]])
print(b)
print(b.shape)
print(b[0,0],b[0,1])

In [ ]:
c=np.array([[1,2],[3,4],[5,6]])
print(c)
print(c[0,0],c[0,1],c[2,0],c[2,1])

[[1 2]
 [3 4]
 [5 6]]
1 2 5 6


In [ ]:
d=np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
e=np.ones((4,2))
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
f=np.full((2,2),9)
print(f)

[[9 9]
 [9 9]]


In [ ]:
g=np.random.random((3,3))
print(g)

[[0.53508049 0.65224055 0.33747543]
 [0.92557416 0.87519918 0.47060827]
 [0.3398651  0.57639306 0.54592793]]


In [ ]:
h=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
i=h[:2,1:3]
print(i)

[[2 3]
 [6 7]]


**18_08_2022**


Data Collection, Modelling 

---



In [3]:
my_dict={'Name':["a","b","c","d","e","f","g"],
         'age':[20,27,35,45,55,43,35],
         'designation':["VP","CEO","CFO","VP","VP","CEO","MD"]}

In [5]:
import pandas as pd
import numpy as np
df=pd.DataFrame(my_dict)
df

Name  age designation
0    a   20          VP
1    b   27         CEO
2    c   35         CFO
3    d   45          VP
4    e   55          VP
5    f   43         CEO
6    g   35          MD

In [6]:
df.to_csv('CSV FILE')