<a href="https://colab.research.google.com/github/shubhamlad21/msc1_fds_512/blob/main/FDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**13_08_2022**

---



In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a=np.array([1,2,3])                                     
print(a)
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3


In [ ]:
b=np.array([[1,2],[3,4]])
print(b)
print(b.shape)
print(b[0,0],b[0,1])

In [ ]:
c=np.array([[1,2],[3,4],[5,6]])
print(c)
print(c[0,0],c[0,1],c[2,0],c[2,1])

[[1 2]
 [3 4]
 [5 6]]
1 2 5 6


In [ ]:
d=np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
e=np.ones((4,2))
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
f=np.full((2,2),9)
print(f)

[[9 9]
 [9 9]]


In [ ]:
g=np.random.random((3,3))
print(g)

[[0.53508049 0.65224055 0.33747543]
 [0.92557416 0.87519918 0.47060827]
 [0.3398651  0.57639306 0.54592793]]


In [ ]:
h=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
i=h[:2,1:3]
print(i)

[[2 3]
 [6 7]]


---

**18_08_2022**

Data Collection, Modelling 

---



In [ ]:
my_dict={'Name':["a","b","c","d","e","f","g"],
         'age':[20,27,35,45,55,43,35],
         'designation':["VP","CEO","CFO","VP","VP","CEO","MD"]}

In [ ]:
import pandas as pd
import numpy as np
df=pd.DataFrame(my_dict)
df

Name  age designation
0    a   20          VP
1    b   27         CEO
2    c   35         CFO
3    d   45          VP
4    e   55          VP
5    f   43         CEO
6    g   35          MD

In [ ]:
df.to_csv('CSV FILE.csv',index=False)

In [ ]:
df_csv=pd.read_csv('CSV FILE.csv')
df_csv

Name  age designation
0    a   20          VP
1    b   27         CEO
2    c   35         CFO
3    d   45          VP
4    e   55          VP
5    f   43         CEO
6    g   35          MD

**20_08_2022**

In [ ]:
import pandas as pd
Location = "student-mat.csv"
df=pd.read_csv(Location,header=None)
df.head()

0    1    2        3        4        5     6     7        8         9   \
0  school  sex  age  address  famsize  Pstatus  Medu  Fedu     Mjob      Fjob   
1      GP    F   18        U      GT3        A     4     4  at_home   teacher   
2      GP    F   17        U      GT3        T     1     1  at_home     other   
3      GP    F   15        U      LE3        T     1     1  at_home     other   
4      GP    F   15        U      GT3        T     4     2   health  services   

   ...      23        24     25    26    27      28        29  30  31  32  
0  ...  famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  G3  
1  ...       4         3      4     1     1       3         6   5   6   6  
2  ...       5         3      3     1     1       3         4   5   5   6  
3  ...       4         3      2     2     3       3        10   7   8  10  
4  ...       3         2      2     1     1       5         2  15  14  15  

[5 rows x 33 columns]

In [ ]:
import pandas as pd
Location = "student-mat.csv"
df=pd.read_csv(Location)
df.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [ ]:
import pandas as pd
Location = "student-mat.csv"
df=pd.read_csv(Location,names=['Roll No','Names','Grades'])
df.columns=['Roll No','Names','Grades']
df.head()

Roll No  \
school sex age address famsize Pstatus Medu Fedu Mjob    Fjob     reason guardian traveltime studytime failures schoolsup famsup paid activities nursery higher internet romantic famrel freetime goout Dalc Walc health absences      G1   
GP     F   18  U       GT3     A       4    4    at_home teacher  course mother   2          2         0        yes       no     no   no         yes     yes    no       no       4      3        4     1    1    3      6              5   
           17  U       GT3     T       1    1    at_home other    course father   1          2         0        no        yes    no   no         no      yes    yes      no       5      3        3     1    1    3      4              5   
           15  U       LE3     T       1    1    at_home other    other  mother   1          2         3        yes       no     yes  no         yes     yes    yes      no       4      3        2     2    3    3      10             7   
                       GT3     T       4    2    health  services home   mother   1          3         0        no        yes    yes  yes        yes     yes    yes      yes      3      2        2     1    1    5      2             15   

                                                                                                                                                                                                                                  Names  \
school sex age address famsize Pstatus Medu Fedu Mjob    Fjob     reason guardian traveltime studytime failures schoolsup famsup paid activities nursery higher internet romantic famrel freetime goout Dalc Walc health absences    G2   
GP     F   18  U       GT3     A       4    4    at_home teacher  course mother   2          2         0        yes       no     no   no         yes     yes    no       no       4      3        4     1    1    3      6            6   
           17  U       GT3     T       1    1    at_home other    course father   1          2         0        no        yes    no   no         no      yes    yes      no       5      3        3     1    1    3      4            5   
           15  U       LE3     T       1    1    at_home other    other  mother   1          2         3        yes       no     yes  no         yes     yes    yes      no       4      3        2     2    3    3      10           8   
                       GT3     T       4    2    health  services home   mother   1          3         0        no        yes    yes  yes        yes     yes    yes      yes      3      2        2     1    1    5      2           14   

                                                                                                                                                                                                                                  Grades  
school sex age address famsize Pstatus Medu Fedu Mjob    Fjob     reason guardian traveltime studytime failures schoolsup famsup paid activities nursery higher internet romantic famrel freetime goout Dalc Walc health absences     G3  
GP     F   18  U       GT3     A       4    4    at_home teacher  course mother   2          2         0        yes       no     no   no         yes     yes    no       no       4      3        4     1    1    3      6             6  
           17  U       GT3     T       1    1    at_home other    course father   1          2         0        no        yes    no   no         no      yes    yes      no       5      3        3     1    1    3      4             6  
           15  U       LE3     T       1    1    at_home other    other  mother   1          2         3        yes       no     yes  no         yes     yes    yes      no       4      3        2     2    3    3      10           10  
                       GT3     T       4    2    health  services home   mother   1          3         0        no        yes    yes  yes        yes     yes    yes      yes      3      2        2     1    1    5      

In [ ]:
import pandas as pd
names=['Bob','Jessica','Mary','John','Mel']
grades=[76,95,77,78,99]
bsdegrees=[1,1,0,0,1]
msdegrees=[2,1,0,0,0]
phddegrees=[0,1,0,0,0]
Degrees=zip(names,grades,bsdegrees,msdegrees,phddegrees)
columns=['Names','Grades','BS','MS','PhD']
df=pd.DataFrame(data=Degrees,columns=columns)
df

Names  Grades  BS  MS  PhD
0      Bob      76   1   2    0
1  Jessica      95   1   1    1
2     Mary      77   0   0    0
3     John      78   0   0    0
4      Mel      99   1   0    0

In [ ]:
csvv=df.to_csv('CSV FILE.csv',index=False)
df_csv=pd.read_csv('CSV FILE.csv')
df_csv

Names  Grades  BS  MS  PhD
0      Bob      76   1   2    0
1  Jessica      95   1   1    1
2     Mary      77   0   0    0
3     John      78   0   0    0
4      Mel      99   1   0    0

In [ ]:
Location="gradedata.xlsx"
#Location="C:/Users/admin/Downloads/Shubham/gradedata.xlsx"
df=pd.read_excel(Location)
#changing column names
df.columns=['first','last','sex','age','exer','hrs','grd','addr']
df.head()

first      last     sex  age  exer  hrs   grd  \
0   Marcia      Pugh  female   17     3   10  82.4   
1   Kadeem  Morrison    male   18     4    4  78.2   
2     Nash    Powell    male   18     5    9  79.3   
3  Noelani    Wagner  female   14     2    7  83.2   
4  Noelani    Cherry  female   18     4   15  87.4   

                                         addr  
0        7379 Highland Rd. , Dublin, GA 31021  
1          8 Bayport St. , Honolulu, HI 96815  
2           Encino, CA 91316, 3 Lilac Street   
3  Riverview, FL 33569, 9998 North Smith Dr.   
4   97 SE. Ocean Street , Bethlehem, PA 18015

To install xlxs writer using anaconda powershell prompt cmd
```
#pip install xlsxwriter
```
There are two options that we have: xlrd and openpyxl.
```
#pip install xlrd
#pip install xlwt openpyxl
```


In [ ]:
!pip install xlsxwriter
import pandas as pd
names=['Bob','Jessica','Mary','John','Mel']
grades=[76,95,77,78,99]
GradeList=zip(names,grades)
df=pd.DataFrame(data=GradeList,columns=['Names','Grades'])

writer=pd.ExcelWriter('dataframe.xlsx',engine='xlsxwriter')
df.to_excel(writer,sheet_name='Sheet 1')
writer.save()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 149 kB 5.3 MB/s 


In [ ]:
import sqlite3
con=sqlite3.connect("portal_mammals.sqlite")
cur=con.cursor()
for row in cur.execute('Select * from species;'):
    print(row)
con.close()

('AB', 'Amphispiza', 'bilineata', 'Bird')
('AH', 'Ammospermophilus', 'harrisi', 'Rodent')
('AS', 'Ammodramus', 'savannarum', 'Bird')
('BA', 'Baiomys', 'taylori', 'Rodent')
('CB', 'Campylorhynchus', 'brunneicapillus', 'Bird')
('CM', 'Calamospiza', 'melanocorys', 'Bird')
('CQ', 'Callipepla', 'squamata', 'Bird')
('CS', 'Crotalus', 'scutalatus', 'Reptile')
('CT', 'Cnemidophorus', 'tigris', 'Reptile')
('CU', 'Cnemidophorus', 'uniparens', 'Reptile')
('CV', 'Crotalus', 'viridis', 'Reptile')
('DM', 'Dipodomys', 'merriami', 'Rodent')
('DO', 'Dipodomys', 'ordii', 'Rodent')
('DS', 'Dipodomys', 'spectabilis', 'Rodent')
('DX', 'Dipodomys', 'sp.', 'Rodent')
('EO', 'Eumeces', 'obsoletus', 'Reptile')
('GS', 'Gambelia', 'silus', 'Reptile')
('NL', 'Neotoma', 'albigula', 'Rodent')
('NX', 'Neotoma', 'sp.', 'Rodent')
('OL', 'Onychomys', 'leucogaster', 'Rodent')
('OT', 'Onychomys', 'torridus', 'Rodent')
('OX', 'Onychomys', 'sp.', 'Rodent')
('PB', 'Chaetodipus', 'baileyi', 'Rodent')
('PC', 'Pipilo', 'chlorur

# **25_08_2022**

In [ ]:
import pandas as pd
names=['Shubham','Mayuresh','Akhil','Vedant','Abhishek']
clss=['msc1','msc2','msc1','msc3','msc5']
roll_no=[512,503,507,515,500]
marks_obtained=[19,17,15,18,12]
result=['Pass','Pass','Pass','Pass','Fail']
MSC=zip(names,clss,roll_no,marks_obtained,result)
columns=['Names','Class','Roll No','Marks','Result']
df=pd.DataFrame(data=MSC,columns=columns)
df
df.to_csv('DataFrame.csv',index=False)

In [ ]:
df_csv=pd.read_csv('DataFrame.csv')
df_csv

Names Class  Roll No  Marks Result
0   Shubham  msc1      512     19   Pass
1  Mayuresh  msc2      503     17   Pass
2     Akhil  msc1      507     15   Pass
3    Vedant  msc3      515     18   Pass
4  Abhishek  msc5      500     12   Fail

In [ ]:
!pip install xlsxwriter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
writer=pd.ExcelWriter('dataframe.xlsx',engine='xlsxwriter')
df.to_excel(writer,sheet_name='Sheet 1')
writer.save()

In [ ]:
df1 = pd.read_excel('dataframe.xlsx')
df1

Unnamed: 0     Names Class  Roll No  Marks Result
0           0   Shubham  msc1      512     19   Pass
1           1  Mayuresh  msc2      503     17   Pass
2           2     Akhil  msc1      507     15   Pass
3           3    Vedant  msc3      515     18   Pass
4           4  Abhishek  msc5      500     12   Fail

# **Data Processing**

In [ ]:
state=pd.read_csv("US_violent_crime.csv")
state.head()

State  Murder  Assault  UrbanPop  Rape
0     Alabama    13.2      236        58  21.2
1      Alaska    10.0      263        48  44.5
2     Arizona     8.1      294        80  31.0
3    Arkansas     8.8      190        50  19.5
4  California     9.0      276        91  40.6

In [ ]:
def some_function(x):
  return x*2
state.apply(some_function) #update each entry of dataframe without any loop
state.apply(lambda n:n*2) #lambda also works the same

State  Murder  Assault  UrbanPop  Rape
0                 AlabamaAlabama    26.4      472       116  42.4
1                   AlaskaAlaska    20.0      526        96  89.0
2                 ArizonaArizona    16.2      588       160  62.0
3               ArkansasArkansas    17.6      380       100  39.0
4           CaliforniaCalifornia    18.0      552       182  81.2
5               ColoradoColorado    15.8      408       156  77.4
6         ConnecticutConnecticut     6.6      220       154  22.2
7               DelawareDelaware    11.8      476       144  31.6
8                 FloridaFlorida    30.8      670       160  63.8
9                 GeorgiaGeorgia    34.8      422       120  51.6
10                  HawaiiHawaii    10.6       92       166  40.4
11                    IdahoIdaho     5.2      240       108  28.4
12              IllinoisIllinois    20.8      498       166  48.0
13                IndianaIndiana    14.4      226       130  42.0
14                      IowaIowa     4.4      112       114  22.6
15                  KansasKansas    12.0      230       132  36.0
16              KentuckyKentucky    19.4      218       104  32.6
17            LouisianaLouisiana    30.8      498       132  44.4
18                    MaineMaine     4.2      166       102  15.6
19              MarylandMaryland    22.6      600       134  55.6
20    MassachusettsMassachusetts     8.8      298       170  32.6
21              MichiganMichigan    24.2      510       148  70.2
22            MinnesotaMinnesota     5.4      144       132  29.8
23        MississippiMississippi    32.2      518        88  34.2
24              MissouriMissouri    18.0      356       140  56.4
25                MontanaMontana    12.0      218       106  32.8
26              NebraskaNebraska     8.6      204       124  33.0
27                  NevadaNevada    24.4      504       162  92.0
28    New HampshireNew Hampshire     4.2      114       112  19.0
29          New JerseyNew Jersey    14.8      318       178  37.6
30          New MexicoNew Mexico    22.8      570       140  64.2
31              New YorkNew York    22.2      508       172  52.2
32  North CarolinaNorth Carolina    26.0      674        90  32.2
33      North DakotaNorth Dakota     1.6       90        88  14.6
34                      OhioOhio    14.6      240       150  42.8
35              OklahomaOklahoma    13.2      302       136  40.0
36                  OregonOregon     9.8      318       134  58.6
37      PennsylvaniaPennsylvania    12.6      212       144  29.8
38      Rhode IslandRhode Island     6.8      348       174  16.6
39  South CarolinaSouth Carolina    28.8      558        96  45.0
40      South DakotaSouth Dakota     7.6      172        90  25.6
41            TennesseeTennessee    26.4      376       118  53.8
42                    TexasTexas    25.4      402       160  51.0
43                      UtahUtah     6.4      240       160  45.8
44                VermontVermont     4.4       96        64  22.4
45              VirginiaVirginia    17.0      312       126  41.4
46          WashingtonWashington     8.0      290       146  52.4
47    West VirginiaWest Virginia    11.4      162        78  18.6
48            WisconsinWisconsin     5.2      106       132  21.6
49                WyomingWyoming    13.6      322       120  31.2

# **26_08_2022**

In [ ]:
import sqlite3
con=sqlite3.connect("portal_mammals.sqlite")
cur=con.cursor()
for row in cur.execute('Select * from species;'):
    print(row)
con.close()

('AB', 'Amphispiza', 'bilineata', 'Bird')
('AH', 'Ammospermophilus', 'harrisi', 'Rodent')
('AS', 'Ammodramus', 'savannarum', 'Bird')
('BA', 'Baiomys', 'taylori', 'Rodent')
('CB', 'Campylorhynchus', 'brunneicapillus', 'Bird')
('CM', 'Calamospiza', 'melanocorys', 'Bird')
('CQ', 'Callipepla', 'squamata', 'Bird')
('CS', 'Crotalus', 'scutalatus', 'Reptile')
('CT', 'Cnemidophorus', 'tigris', 'Reptile')
('CU', 'Cnemidophorus', 'uniparens', 'Reptile')
('CV', 'Crotalus', 'viridis', 'Reptile')
('DM', 'Dipodomys', 'merriami', 'Rodent')
('DO', 'Dipodomys', 'ordii', 'Rodent')
('DS', 'Dipodomys', 'spectabilis', 'Rodent')
('DX', 'Dipodomys', 'sp.', 'Rodent')
('EO', 'Eumeces', 'obsoletus', 'Reptile')
('GS', 'Gambelia', 'silus', 'Reptile')
('NL', 'Neotoma', 'albigula', 'Rodent')
('NX', 'Neotoma', 'sp.', 'Rodent')
('OL', 'Onychomys', 'leucogaster', 'Rodent')
('OT', 'Onychomys', 'torridus', 'Rodent')
('OX', 'Onychomys', 'sp.', 'Rodent')
('PB', 'Chaetodipus', 'baileyi', 'Rodent')
('PC', 'Pipilo', 'chlorur

In [ ]:
import sqlite3
con=sqlite3.connect("portal_mammals.sqlite")
cur=con.cursor()
cur.execute('SELECT plot_id from plots where plot_type="Control"');
print(cur.fetchall())

cur.execute('SELECT species from species where taxa="Bird"');
print(cur.fetchone())

con.close()

[(2,), (4,), (8,), (11,), (12,), (14,), (17,), (22,)]
('bilineata',)


In [ ]:
import pandas as pd
import sqlite3
#read sqlite query results into a pandas DataFrame
con=sqlite3.connect("portal_mammals.sqlite")
df=pd.read_sql_query("SELECT * FROM surveys",con)
print(df.head())
con.close()

   record_id  month  day  year  plot_id species_id sex  hindfoot_length  \
0          1      7   16  1977        2         NL   M             32.0   
1          2      7   16  1977        3         NL   M             33.0   
2          3      7   16  1977        2         DM   F             37.0   
3          4      7   16  1977        7         DM   M             36.0   
4          5      7   16  1977        3         DM   M             35.0   

   weight  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  


In [ ]:
from pandas import DataFrame
Cars={'Brand':['Honda Civic','Toyota Carolla','Ford Focus','Audi A4'],
      'Price':[22000,25000,27000,35000]}
df=DataFrame(Cars,columns=['Brand','Price'])
print(df)

            Brand  Price
0     Honda Civic  22000
1  Toyota Carolla  25000
2      Ford Focus  27000
3         Audi A4  35000


In [ ]:
import sqlite3
conn=sqlite3.connect("TestDB")
c=conn.cursor()
c.execute('create table cars2(Brand Text,Price Number)')
conn.commit()

In [ ]:
df.to_sql('cars2',conn,if_exists='replace',index=False)
df

Brand  Price
0     Honda Civic  22000
1  Toyota Carolla  25000
2      Ford Focus  27000
3         Audi A4  35000

In [ ]:
c.execute('''
select Brand,max(Price) from cars2
''')

In [ ]:
df=DataFrame(c.fetchall(),columns=['Brand','Price'])
df

Brand  Price
0  Audi A4  35000

In [ ]:
import sqlite3
from sqlalchemy import create_engine
db_filename=r'studentdata.db'
con=sqlite3.connect(db_filename)
df.to_sql('student',
          con,
          schema=None,
          if_exists='replace',
          index=True,
          index_label=None,
          chunksize=None,
          dtype=None)
con.close()
db_file=r'studentdata.db'
engine=create_engine(r'sqlite:///{}' .format(db_file))
sql='select * from student'
studf=pd.read_sql(sql,engine)
studf

index    Brand  Price
0      0  Audi A4  35000

In [ ]:
import pandas as pd
stud_id=['rj101','rj102','rj103','rj104','rj105']
sname=['Saurabh','Giftson','Vikas','Radha','Arya']
lname=['Chavan','Paul','Bisol','Ral','Khan']
dept=['Bms','Bcom','Bcs','Bsc IT','Bcs']
email=['saurabh@gmail.com','giftson@gmail.com','vikas@gmail.com','radha@gmail.com','arya@gmail.com']

stud_data=zip(stud_id,sname,lname,dept,email)
columns=['Names','Grades','BS','MS','PhD']
df=pd.DataFrame(data=stud_data,columns=['stud_id','sname','lname','dept','email'])
df

stud_id    sname   lname    dept              email
0   rj101  Saurabh  Chavan     Bms  saurabh@gmail.com
1   rj102  Giftson    Paul    Bcom  giftson@gmail.com
2   rj103    Vikas   Bisol     Bcs    vikas@gmail.com
3   rj104    Radha     Ral  Bsc IT    radha@gmail.com
4   rj105     Arya    Khan     Bcs     arya@gmail.com

In [3]:
import pandas as pd
state=pd.read_csv("US_violent_crime.csv")
state.head()
def some_func(x):
  return x*2
state.apply(some_func)
state.apply(lambda n:n*2)

State  Murder  Assault  UrbanPop  Rape
0                 AlabamaAlabama    26.4      472       116  42.4
1                   AlaskaAlaska    20.0      526        96  89.0
2                 ArizonaArizona    16.2      588       160  62.0
3               ArkansasArkansas    17.6      380       100  39.0
4           CaliforniaCalifornia    18.0      552       182  81.2
5               ColoradoColorado    15.8      408       156  77.4
6         ConnecticutConnecticut     6.6      220       154  22.2
7               DelawareDelaware    11.8      476       144  31.6
8                 FloridaFlorida    30.8      670       160  63.8
9                 GeorgiaGeorgia    34.8      422       120  51.6
10                  HawaiiHawaii    10.6       92       166  40.4
11                    IdahoIdaho     5.2      240       108  28.4
12              IllinoisIllinois    20.8      498       166  48.0
13                IndianaIndiana    14.4      226       130  42.0
14                      IowaIowa     4.4      112       114  22.6
15                  KansasKansas    12.0      230       132  36.0
16              KentuckyKentucky    19.4      218       104  32.6
17            LouisianaLouisiana    30.8      498       132  44.4
18                    MaineMaine     4.2      166       102  15.6
19              MarylandMaryland    22.6      600       134  55.6
20    MassachusettsMassachusetts     8.8      298       170  32.6
21              MichiganMichigan    24.2      510       148  70.2
22            MinnesotaMinnesota     5.4      144       132  29.8
23        MississippiMississippi    32.2      518        88  34.2
24              MissouriMissouri    18.0      356       140  56.4
25                MontanaMontana    12.0      218       106  32.8
26              NebraskaNebraska     8.6      204       124  33.0
27                  NevadaNevada    24.4      504       162  92.0
28    New HampshireNew Hampshire     4.2      114       112  19.0
29          New JerseyNew Jersey    14.8      318       178  37.6
30          New MexicoNew Mexico    22.8      570       140  64.2
31              New YorkNew York    22.2      508       172  52.2
32  North CarolinaNorth Carolina    26.0      674        90  32.2
33      North DakotaNorth Dakota     1.6       90        88  14.6
34                      OhioOhio    14.6      240       150  42.8
35              OklahomaOklahoma    13.2      302       136  40.0
36                  OregonOregon     9.8      318       134  58.6
37      PennsylvaniaPennsylvania    12.6      212       144  29.8
38      Rhode IslandRhode Island     6.8      348       174  16.6
39  South CarolinaSouth Carolina    28.8      558        96  45.0
40      South DakotaSouth Dakota     7.6      172        90  25.6
41            TennesseeTennessee    26.4      376       118  53.8
42                    TexasTexas    25.4      402       160  51.0
43                      UtahUtah     6.4      240       160  45.8
44                VermontVermont     4.4       96        64  22.4
45              VirginiaVirginia    17.0      312       126  41.4
46          WashingtonWashington     8.0      290       146  52.4
47    West VirginiaWest Virginia    11.4      162        78  18.6
48            WisconsinWisconsin     5.2      106       132  21.6
49                WyomingWyoming    13.6      322       120  31.2

# **08/09/2022**

In [4]:
state.transform(func=lambda x:x*10)

State  Murder  Assault  \
0   AlabamaAlabamaAlabamaAlabamaAlabamaAlabamaAlab...   132.0     2360   
1   AlaskaAlaskaAlaskaAlaskaAlaskaAlaskaAlaskaAlas...   100.0     2630   
2   ArizonaArizonaArizonaArizonaArizonaArizonaAriz...    81.0     2940   
3   ArkansasArkansasArkansasArkansasArkansasArkans...    88.0     1900   
4   CaliforniaCaliforniaCaliforniaCaliforniaCalifo...    90.0     2760   
5   ColoradoColoradoColoradoColoradoColoradoColora...    79.0     2040   
6   ConnecticutConnecticutConnecticutConnecticutCo...    33.0     1100   
7   DelawareDelawareDelawareDelawareDelawareDelawa...    59.0     2380   
8   FloridaFloridaFloridaFloridaFloridaFloridaFlor...   154.0     3350   
9   GeorgiaGeorgiaGeorgiaGeorgiaGeorgiaGeorgiaGeor...   174.0     2110   
10  HawaiiHawaiiHawaiiHawaiiHawaiiHawaiiHawaiiHawa...    53.0      460   
11  IdahoIdahoIdahoIdahoIdahoIdahoIdahoIdahoIdahoI...    26.0     1200   
12  IllinoisIllinoisIllinoisIllinoisIllinoisIllino...   104.0     2490   
13  IndianaIndianaIndianaIndianaIndianaIndianaIndi...    72.0     1130   
14           IowaIowaIowaIowaIowaIowaIowaIowaIowaIowa    22.0      560   
15  KansasKansasKansasKansasKansasKansasKansasKans...    60.0     1150   
16  KentuckyKentuckyKentuckyKentuckyKentuckyKentuc...    97.0     1090   
17  LouisianaLouisianaLouisianaLouisianaLouisianaL...   154.0     2490   
18  MaineMaineMaineMaineMaineMaineMaineMaineMaineM...    21.0      830   
19  MarylandMarylandMarylandMarylandMarylandMaryla...   113.0     3000   
20  MassachusettsMassachusettsMassachusettsMassach...    44.0     1490   
21  MichiganMichiganMichiganMichiganMichiganMichig...   121.0     2550   
22  MinnesotaMinnesotaMinnesotaMinnesotaMinnesotaM...    27.0      720   
23  MississippiMississippiMississippiMississippiMi...   161.0     2590   
24  MissouriMissouriMissouriMissouriMissouriMissou...    90.0     1780   
25  MontanaMontanaMontanaMontanaMontanaMontanaMont...    60.0     1090   
26  NebraskaNebraskaNebraskaNebraskaNebraskaNebras...    43.0     1020   
27  NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...   122.0     2520   
28  New HampshireNew HampshireNew HampshireNew Ham...    21.0      570   
29  New JerseyNew JerseyNew JerseyNew JerseyNew Je...    74.0     1590   
30  New MexicoNew MexicoNew MexicoNew MexicoNew Me...   114.0     2850   
31  New YorkNew YorkNew YorkNew YorkNew YorkNew Yo...   111.0     2540   
32  North CarolinaNorth CarolinaNorth CarolinaNort...   130.0     3370   
33  North DakotaNorth DakotaNorth DakotaNorth Dako...     8.0      450   
34           OhioOhioOhioOhioOhioOhioOhioOhioOhioOhio    73.0     1200   
35  OklahomaOklahomaOklahomaOklahomaOklahomaOklaho...    66.0     1510   
36  OregonOregonOregonOregonOregonOregonOregonOreg...    49.0     1590   
37  PennsylvaniaPennsylvaniaPennsylvaniaPennsylvan...    63.0     1060   
38  Rhode IslandRhode IslandRhode IslandRhode Isla...    34.0     1740   
39  South CarolinaSouth CarolinaSouth CarolinaSout...   144.0     2790   
40  South DakotaSouth DakotaSouth DakotaSouth Dako...    38.0      860   
41  TennesseeTennesseeTennesseeTennesseeTennesseeT...   132.0     1880   
42  TexasTexasTexasTexasTexasTexasTexasTexasTexasT...   127.0     2010   
43           UtahUtahUtahUtahUtahUtahUtahUtahUtahUtah    32.0     1200   
44  VermontVermontVermontVermontVermontVermontVerm...    22.0      480   
45  VirginiaVirginiaVirginiaVirginiaVirginiaVirgin...    85.0     1560   
46  WashingtonWashingtonWashingtonWashingtonWashin...    40.0     1450   
47  West VirginiaWest VirginiaWest VirginiaWest Vi...    57.0      810   
48  WisconsinWisconsinWisconsinWisconsinWisconsinW...    26.0      530   
49  WyomingWyomingWyomingWyomingWyomingWyomingWyom...    68.0     1610   

    UrbanPop   Rape  
0        580  212.0  
1        480  445.0  
2        800  310.0  
3        500  195.0  
4        910  406.0  
5        780  387.0  
6        770  111.0  
7        720  158.0  
8        800  319.0  
9        600  258.0  
10       830  202.0  
11       