<a href="https://colab.research.google.com/github/shubhamlad21/msc1_fds_512/blob/main/FDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**13_08_2022**

---



In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a=np.array([1,2,3])                                     
print(a)
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3


In [ ]:
b=np.array([[1,2],[3,4]])
print(b)
print(b.shape)
print(b[0,0],b[0,1])

In [ ]:
c=np.array([[1,2],[3,4],[5,6]])
print(c)
print(c[0,0],c[0,1],c[2,0],c[2,1])

[[1 2]
 [3 4]
 [5 6]]
1 2 5 6


In [ ]:
d=np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
e=np.ones((4,2))
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
f=np.full((2,2),9)
print(f)

[[9 9]
 [9 9]]


In [ ]:
g=np.random.random((3,3))
print(g)

[[0.53508049 0.65224055 0.33747543]
 [0.92557416 0.87519918 0.47060827]
 [0.3398651  0.57639306 0.54592793]]


In [ ]:
h=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
i=h[:2,1:3]
print(i)

[[2 3]
 [6 7]]


---

**18_08_2022**

Data Collection, Modelling 

---



In [ ]:
my_dict={'Name':["a","b","c","d","e","f","g"],
         'age':[20,27,35,45,55,43,35],
         'designation':["VP","CEO","CFO","VP","VP","CEO","MD"]}

In [ ]:
import pandas as pd
import numpy as np
df=pd.DataFrame(my_dict)
df

Name  age designation
0    a   20          VP
1    b   27         CEO
2    c   35         CFO
3    d   45          VP
4    e   55          VP
5    f   43         CEO
6    g   35          MD

In [ ]:
df.to_csv('CSV FILE.csv',index=False)

In [ ]:
df_csv=pd.read_csv('CSV FILE.csv')
df_csv

Name  age designation
0    a   20          VP
1    b   27         CEO
2    c   35         CFO
3    d   45          VP
4    e   55          VP
5    f   43         CEO
6    g   35          MD

**20_08_2022**

In [ ]:
import pandas as pd
Location = "student-mat.csv"
df=pd.read_csv(Location,header=None)
df.head()

0    1    2        3        4        5     6     7        8         9   \
0  school  sex  age  address  famsize  Pstatus  Medu  Fedu     Mjob      Fjob   
1      GP    F   18        U      GT3        A     4     4  at_home   teacher   
2      GP    F   17        U      GT3        T     1     1  at_home     other   
3      GP    F   15        U      LE3        T     1     1  at_home     other   
4      GP    F   15        U      GT3        T     4     2   health  services   

   ...      23        24     25    26    27      28        29  30  31  32  
0  ...  famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  G3  
1  ...       4         3      4     1     1       3         6   5   6   6  
2  ...       5         3      3     1     1       3         4   5   5   6  
3  ...       4         3      2     2     3       3        10   7   8  10  
4  ...       3         2      2     1     1       5         2  15  14  15  

[5 rows x 33 columns]

In [ ]:
import pandas as pd
Location = "student-mat.csv"
df=pd.read_csv(Location)
df.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [ ]:
import pandas as pd
Location = "student-mat.csv"
df=pd.read_csv(Location,names=['Roll No','Names','Grades'])
df.columns=['Roll No','Names','Grades']
df.head()

Roll No  \
school sex age address famsize Pstatus Medu Fedu Mjob    Fjob     reason guardian traveltime studytime failures schoolsup famsup paid activities nursery higher internet romantic famrel freetime goout Dalc Walc health absences      G1   
GP     F   18  U       GT3     A       4    4    at_home teacher  course mother   2          2         0        yes       no     no   no         yes     yes    no       no       4      3        4     1    1    3      6              5   
           17  U       GT3     T       1    1    at_home other    course father   1          2         0        no        yes    no   no         no      yes    yes      no       5      3        3     1    1    3      4              5   
           15  U       LE3     T       1    1    at_home other    other  mother   1          2         3        yes       no     yes  no         yes     yes    yes      no       4      3        2     2    3    3      10             7   
                       GT3     T       4    2    health  services home   mother   1          3         0        no        yes    yes  yes        yes     yes    yes      yes      3      2        2     1    1    5      2             15   

                                                                                                                                                                                                                                  Names  \
school sex age address famsize Pstatus Medu Fedu Mjob    Fjob     reason guardian traveltime studytime failures schoolsup famsup paid activities nursery higher internet romantic famrel freetime goout Dalc Walc health absences    G2   
GP     F   18  U       GT3     A       4    4    at_home teacher  course mother   2          2         0        yes       no     no   no         yes     yes    no       no       4      3        4     1    1    3      6            6   
           17  U       GT3     T       1    1    at_home other    course father   1          2         0        no        yes    no   no         no      yes    yes      no       5      3        3     1    1    3      4            5   
           15  U       LE3     T       1    1    at_home other    other  mother   1          2         3        yes       no     yes  no         yes     yes    yes      no       4      3        2     2    3    3      10           8   
                       GT3     T       4    2    health  services home   mother   1          3         0        no        yes    yes  yes        yes     yes    yes      yes      3      2        2     1    1    5      2           14   

                                                                                                                                                                                                                                  Grades  
school sex age address famsize Pstatus Medu Fedu Mjob    Fjob     reason guardian traveltime studytime failures schoolsup famsup paid activities nursery higher internet romantic famrel freetime goout Dalc Walc health absences     G3  
GP     F   18  U       GT3     A       4    4    at_home teacher  course mother   2          2         0        yes       no     no   no         yes     yes    no       no       4      3        4     1    1    3      6             6  
           17  U       GT3     T       1    1    at_home other    course father   1          2         0        no        yes    no   no         no      yes    yes      no       5      3        3     1    1    3      4             6  
           15  U       LE3     T       1    1    at_home other    other  mother   1          2         3        yes       no     yes  no         yes     yes    yes      no       4      3        2     2    3    3      10           10  
                       GT3     T       4    2    health  services home   mother   1          3         0        no        yes    yes  yes        yes     yes    yes      yes      3      2        2     1    1    5      

In [ ]:
import pandas as pd
names=['Bob','Jessica','Mary','John','Mel']
grades=[76,95,77,78,99]
bsdegrees=[1,1,0,0,1]
msdegrees=[2,1,0,0,0]
phddegrees=[0,1,0,0,0]
Degrees=zip(names,grades,bsdegrees,msdegrees,phddegrees)
columns=['Names','Grades','BS','MS','PhD']
df=pd.DataFrame(data=Degrees,columns=columns)
df

Names  Grades  BS  MS  PhD
0      Bob      76   1   2    0
1  Jessica      95   1   1    1
2     Mary      77   0   0    0
3     John      78   0   0    0
4      Mel      99   1   0    0

In [ ]:
csvv=df.to_csv('CSV FILE.csv',index=False)
df_csv=pd.read_csv('CSV FILE.csv')
df_csv

Names  Grades  BS  MS  PhD
0      Bob      76   1   2    0
1  Jessica      95   1   1    1
2     Mary      77   0   0    0
3     John      78   0   0    0
4      Mel      99   1   0    0

In [ ]:
Location="gradedata.xlsx"
#Location="C:/Users/admin/Downloads/Shubham/gradedata.xlsx"
df=pd.read_excel(Location)
#changing column names
df.columns=['first','last','sex','age','exer','hrs','grd','addr']
df.head()

first      last     sex  age  exer  hrs   grd  \
0   Marcia      Pugh  female   17     3   10  82.4   
1   Kadeem  Morrison    male   18     4    4  78.2   
2     Nash    Powell    male   18     5    9  79.3   
3  Noelani    Wagner  female   14     2    7  83.2   
4  Noelani    Cherry  female   18     4   15  87.4   

                                         addr  
0        7379 Highland Rd. , Dublin, GA 31021  
1          8 Bayport St. , Honolulu, HI 96815  
2           Encino, CA 91316, 3 Lilac Street   
3  Riverview, FL 33569, 9998 North Smith Dr.   
4   97 SE. Ocean Street , Bethlehem, PA 18015

To install xlxs writer using anaconda powershell prompt cmd
```
#pip install xlsxwriter
```
There are two options that we have: xlrd and openpyxl.
```
#pip install xlrd
#pip install xlwt openpyxl
```


In [ ]:
!pip install xlsxwriter
import pandas as pd
names=['Bob','Jessica','Mary','John','Mel']
grades=[76,95,77,78,99]
GradeList=zip(names,grades)
df=pd.DataFrame(data=GradeList,columns=['Names','Grades'])

writer=pd.ExcelWriter('dataframe.xlsx',engine='xlsxwriter')
df.to_excel(writer,sheet_name='Sheet 1')
writer.save()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 149 kB 5.3 MB/s 


In [ ]:
import sqlite3
con=sqlite3.connect("portal_mammals.sqlite")
cur=con.cursor()
for row in cur.execute('Select * from species;'):
    print(row)
con.close()

('AB', 'Amphispiza', 'bilineata', 'Bird')
('AH', 'Ammospermophilus', 'harrisi', 'Rodent')
('AS', 'Ammodramus', 'savannarum', 'Bird')
('BA', 'Baiomys', 'taylori', 'Rodent')
('CB', 'Campylorhynchus', 'brunneicapillus', 'Bird')
('CM', 'Calamospiza', 'melanocorys', 'Bird')
('CQ', 'Callipepla', 'squamata', 'Bird')
('CS', 'Crotalus', 'scutalatus', 'Reptile')
('CT', 'Cnemidophorus', 'tigris', 'Reptile')
('CU', 'Cnemidophorus', 'uniparens', 'Reptile')
('CV', 'Crotalus', 'viridis', 'Reptile')
('DM', 'Dipodomys', 'merriami', 'Rodent')
('DO', 'Dipodomys', 'ordii', 'Rodent')
('DS', 'Dipodomys', 'spectabilis', 'Rodent')
('DX', 'Dipodomys', 'sp.', 'Rodent')
('EO', 'Eumeces', 'obsoletus', 'Reptile')
('GS', 'Gambelia', 'silus', 'Reptile')
('NL', 'Neotoma', 'albigula', 'Rodent')
('NX', 'Neotoma', 'sp.', 'Rodent')
('OL', 'Onychomys', 'leucogaster', 'Rodent')
('OT', 'Onychomys', 'torridus', 'Rodent')
('OX', 'Onychomys', 'sp.', 'Rodent')
('PB', 'Chaetodipus', 'baileyi', 'Rodent')
('PC', 'Pipilo', 'chlorur

# **25_08_2022**

In [17]:
import pandas as pd
names=['Shubham','Mayuresh','Akhil','Vedant','Abhishek']
clss=['msc1','msc2','msc1','msc3','msc5']
roll_no=[512,503,507,515,500]
marks_obtained=[19,17,15,18,12]
result=['Pass','Pass','Pass','Pass','Fail']
MSC=zip(names,clss,roll_no,marks_obtained,result)
columns=['Names','Class','Roll No','Marks','Result']
df=pd.DataFrame(data=MSC,columns=columns)
df
df.to_csv('DataFrame.csv',index=False)

In [18]:
df_csv=pd.read_csv('DataFrame.csv')
df_csv

Names Class  Roll No  Marks Result
0   Shubham  msc1      512     19   Pass
1  Mayuresh  msc2      503     17   Pass
2     Akhil  msc1      507     15   Pass
3    Vedant  msc3      515     18   Pass
4  Abhishek  msc5      500     12   Fail

In [21]:
!pip install xlsxwriter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [30]:
import pandas as pd
writer=pd.ExcelWriter('dataframe.xlsx',engine='xlsxwriter')
df.to_excel(writer,sheet_name='Sheet 1')
writer.save()

In [31]:
df1 = pd.read_excel('dataframe.xlsx')
df1

Unnamed: 0     Names Class  Roll No  Marks Result
0           0   Shubham  msc1      512     19   Pass
1           1  Mayuresh  msc2      503     17   Pass
2           2     Akhil  msc1      507     15   Pass
3           3    Vedant  msc3      515     18   Pass
4           4  Abhishek  msc5      500     12   Fail